Fix missing body statements check
When running on the opf/openproject frontend, tplant errors out with the following error:

```
/home/b12f/.local/share/nvm/versions/node/v12.18.4/lib/node_modules/tplant/dist/Factories/NamespaceFactory.js:15
        if (declaration === undefined || declaration.body.statements === undefined) {
                                                          ^

TypeError: Cannot read property 'statements' of undefined
    at Object.create (/home/b12f/.local/share/nvm/versions/node/v12.18.4/lib/node_modules/tplant/dist/Factories/NamespaceFactory.js:15:59)
    at /home/b12f/.local/share/nvm/versions/node/v12.18.4/lib/node_modules/tplant/dist/Factories/ComponentFactory.js:54:78
    at visitNodes (/home/b12f/.local/share/nvm/versions/node/v12.18.4/lib/node_modules/tplant/node_modules/typescript/lib/typescript.js:27037:30)
    at Object.forEachChild (/home/b12f/.local/share/nvm/versions/node/v12.18.4/lib/node_modules/tplant/node_modules/typescript/lib/typescript.js:27275:24)
    at Object.create (/home/b12f/.local/share/nvm/versions/node/v12.18.4/lib/node_modules/tplant/dist/Factories/ComponentFactory.js:25:30)
    at Object.create (/home/b12f/.local/share/nvm/versions/node/v12.18.4/lib/node_modules/tplant/dist/Factories/FileFactory.js:10:58)
    at /home/b12f/.local/share/nvm/versions/node/v12.18.4/lib/node_modules/tplant/dist/tplant.js:45:54
    at Array.forEach (<anonymous>)
    at Object.generateDocumentation (/home/b12f/.local/share/nvm/versions/node/v12.18.4/lib/node_modules/tplant/dist/tplant.js:43:14)
    at /home/b12f/.local/share/nvm/versions/node/v12.18.4/lib/node_modules/tplant/dist/index.js:36:75
```

This change fixes the issue.